name: Deploy repo to EC2

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      USER_NAME: ${{ secrets.USER_NAME }}

    steps:
      - name: Checkout code
        uses: appleboy/ssh-action@v0.1.0
        with:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Git pull from EC2 for push cahnges
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.USER_NAME }}@${{ env.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/CSVManagement
            git checkout dev
            git pull
          EOF
