name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: EC2 Deploy

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH keys
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Step 3: SSH connect for Git Pull
      - name: SSH connect for Git Pull
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/CSVManagement || exit
            git checkout dev || exit
            git pull || exit
          EOF
