name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: EC2 Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: SSH connect for Git Pull
        run: |
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} << 'EOF'
            cd /home/ubuntu/CSVManagement || exit
            git checkout dev || exit
            git pull || exit
          EOF
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
