name: Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Deploy to EC2
  
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v4
        - uses: webfactory/ssh-agent@v0.9.0
          with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}

        - uses: actions/checkout@v4
        - name: ssh
      
          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
                cd /home/ubuntu/CSVManagement &&
                git checkout dev &&
                git pull
                '
